spring:
  datasource:
    username: hsp
    password: 123456
    url: jdbc:h2:file:~/.npc/npc
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
    continue-on-error: true
  mvc:
    static-path-pattern: /static/**
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    active: mac
